const icons={
 piano:'M4 4h16v16H4zM9 4v9M15 4v9M9 16v4M15 16v4M7 4v8h3V4M14 4v8h3V4',
 tuner:'M5 4v7a7 7 0 0 0 14 0V4M12 18v4',
 tone:'M4 12h3l3-7 4 14 3-7h3',
 settings:'M4 7h16M4 17h16M8 4v6M16 14v6',
 system:'M3 4h18v13H3zM8 21h8M12 17v4',
 sun:'M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 1.4 1.4M17 17l1.4 1.4M5.6 18.4 1.4-1.4M17 7l1.4-1.4',
 moon:'M20 15A8 8 0 0 1 9 4a8 8 0 1 0 11 11Z',
 pause:'M8 5v14M16 5v14',play:'M8 5l11 7-11 7Z',
 check:'M5 12l4 4L19 6',up:'M12 20V4M6 10l6-6 6 6',down:'M12 4v16M6 14l6 6 6-6',
 info:'M12 11v6M12 7v.1',mic:'M9 5a3 3 0 0 1 6 0v7a3 3 0 0 1-6 0ZM6 11v1a6 6 0 0 0 12 0v-1M12 18v4',
 chevron:'M9 5l7 7-7 7',back:'M14 5l-7 7 7 7',alert:'M12 4l9 16H3ZM12 9v5M12 17v.1',stop:'M6 6h12v12H6z'
};
function icon(name){return `<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[name]||icons.info}"/>${name==='sun'?'<circle cx="12" cy="12" r="4"/>':''}</svg>`}
const reading={flat:{cents:-2.4,label:'Raise pitch',hint:'Bring the marker toward the center.',symbol:'up'},sharp:{cents:3.1,label:'Lower pitch',hint:'Bring the marker toward the center.',symbol:'down'},target:{cents:.2,label:'On target',hint:'Pitch stable · check after releasing the hammer.',symbol:'check',kind:'success'},drift:{cents:.7,label:'Pitch drifting',hint:'Release the hammer, then check again.',symbol:'alert',kind:'warning'},waiting:{cents:null,label:'Play the selected note',hint:'Listening for one isolated string.',symbol:'mic'},weak:{cents:null,label:'Play the note again',hint:'The signal is too weak for a reliable reading.',symbol:'mic',kind:'warning'}};
const $=s=>document.querySelector(s);let timers=[];
function meter(value){return `<svg viewBox="0 0 340 100" aria-label="Pitch scale from 20 cents flat to 20 cents sharp" role="img"><rect x="158" y="17" width="24" height="46" rx="5" fill="var(--selected)"/><path d="M20 40H320" stroke="var(--border-subtle)"/>${[20,57.5,95,132.5,170,207.5,245,282.5,320].map((x,i)=>`<path d="M${x} ${i===4?20:32}V${i===4?62:48}" stroke="${i===4?'var(--primary)':'var(--border-subtle)'}" stroke-width="${i===4?2:1}"/>`).join('')}<g class="needle" style="transform:translateX(${(value||0)*7.5}px);opacity:${value===null?0:1}"><path d="M170 15V62" stroke="var(--primary)" stroke-width="3"/><circle cx="170" cy="15" r="5" fill="var(--primary)"/></g><g class="scale-label" text-anchor="middle"><text x="20" y="83">−20</text><text x="95" y="83">−10</text><text x="170" y="83">0</text><text x="245" y="83">+10</text><text x="320" y="83">+20</text></g></svg>`}
function nav(){return `<nav class="navigation" aria-label="Proposed navigation">${[['tuner','Tuner'],['piano','Piano'],['tone','Tone'],['settings','Settings']].map(([i,l])=>`<div class="nav-item ${i==='piano'?'active':''}" ${i==='piano'?'aria-current="page"':''}>${icon(i)}${l}</div>`).join('')}</nav><div class="home-indicator"></div>`}
function shell(type,theme){return `<section class="specimen"><h2>${type==='tune'?'01 / Piano tuning':'02 / Calibration'} · ${theme==='light'?'Light':'Dark'}</h2><div class="phone" data-type="${type}" data-theme="${theme}" data-original-theme="${theme}"><div class="system"><span>9:41</span><span aria-hidden="true">▰ ▰ ▰</span></div><header class="app-head"><img class="brand" src="../brand/accordomi.svg" alt=""><span class="brand-name">Accordomi</span><button class="icon-button appearance" aria-label="Choose appearance">${icon(theme==='light'?'sun':'moon')}</button><div class="seam" aria-hidden="true"><i></i><i></i><i></i></div></header><div class="content"></div><div class="actions"></div>${nav()}</div></section>`}
$('#screens').innerHTML=['tune','calibrate'].flatMap(t=>['light','dark'].map(m=>shell(t,m))).join('');
const notes=['A0','A1','A2','A3','C4','A4','A5','E6','A6'];
function noteHtml(n){return n.slice(0,-1)+`<sub>${n.slice(-1)}</sub>`}
function noteName(m){const n=['C','C♯','D','D♯','E','F','F♯','G','G♯','A','A♯','B'];return n[m%12]+(Math.floor(m/12)-1)}
function renderTune(p){const state=p.paused?{...reading.waiting,label:'Listening paused',hint:'Resume when you are ready.',symbol:'pause'}:reading[$('#state').value];const n=noteName(p.midi),target=440*Math.pow(2,(p.midi-69)/12),current=state.cents===null?'—':(target*Math.pow(2,state.cents/1200)).toFixed(2)+' Hz';
p.querySelector('.content').innerHTML=`<div class="context"><div><h3>Living room upright</h3><p class="subtle">Piano tuning · A4 = 440 Hz</p></div><button class="text-button details">Details ${icon('chevron')}</button></div><div class="note-area"><div class="overline">Selected note</div><div class="note">${noteHtml(n)}</div><div class="cents">${state.cents===null?'—':(state.cents>=0?'+':'')+state.cents.toFixed(1)} <small>cents</small></div></div><div class="meter">${meter(state.cents)}</div><div class="status ${state.kind||''}" aria-live="polite"><strong>${icon(state.symbol)}${state.label}</strong><p>${state.hint}</p></div><div class="stats"><div><span>Piano target</span><strong>${target.toFixed(2)} Hz</strong></div><div><span>Current pitch</span><strong>${current}</strong></div></div><div class="quality">${icon(state.cents===null?'mic':'check')} ${state.cents===null?'Waiting for a usable signal':'Clear signal · 5 partials agree'}</div>`;
p.querySelector('.actions').innerHTML=`<div class="note-controls"><button class="octave" data-step="-12" ${p.midi<=21?'disabled':''} aria-label="Previous octave">− Octave</button><button data-step="-1" ${p.midi<=21?'disabled':''} aria-label="Previous note">‹ ${noteName(Math.max(21,p.midi-1))}</button><button data-step="1" ${p.midi>=108?'disabled':''} aria-label="Next note">${noteName(Math.min(108,p.midi+1))} ›</button><button class="octave" data-step="12" ${p.midi>=108?'disabled':''} aria-label="Next octave">+ Octave</button></div><button class="${p.paused?'primary':'secondary'} listen">${icon(p.paused?'play':'pause')}${p.paused?'Resume listening':'Pause listening'}</button>`;
}
function renderCal(p){const done=p.index>=9,n=notes[Math.min(p.index,8)],busy=p.recording,accepted=p.take===2;let heading=done?'Your piano is calibrated':busy?'Play once, then let it ring':accepted?'Both strikes agree':p.take===1?'First strike accepted':'Ready for the first strike';let hint=done?'Your piano-specific targets are ready to calculate.':busy?'Listening and checking the partials…':accepted?'This note is saved. Continue when you are ready.':p.take===1?'Wait for silence before recording the second strike.':'Press Record, then play the selected note once.';
p.querySelector('.content').innerHTML=`<div class="overline">Living room upright</div><h3 class="cal-title">Calibrate your piano</h3><p class="subtle">Two separate strikes for each note.</p><div class="progress-heading"><strong>${Math.min(9,p.index+(accepted?1:0))} of 9 notes saved</strong><span>${done?'Complete':`Note ${p.index+1} of 9`}</span></div><div class="progress" aria-label="${Math.min(9,p.index+(accepted?1:0))} of 9 notes saved">${notes.map((_,i)=>`<i class="${i<p.index||(i===p.index&&accepted)?'complete':i===p.index?'current':''}"></i>`).join('')}</div><div class="note-area cal-note"><div class="overline">${done?'All notes measured':'Play this note'}</div><div class="note">${done?'✓':noteHtml(n)}</div></div><div class="strike-pills"><span class="active">${p.take>0?'✓':'1'} First strike</span><span class="${p.take>0?'active':''}">${accepted?'✓':'2'} Second strike</span></div><div class="instruction"><h4>${icon('piano')}One string at a time</h4><p>Mute the other strings of this note and release the sustain pedal. Let each strike decay naturally.</p></div><div class="capture-status" aria-live="polite"><strong>${heading}</strong><p>${hint}</p></div><p class="saved-hint">Completed notes are saved automatically.</p>`;
p.querySelector('.actions').innerHTML=`<p class="cal-footnote">${done?'Reference pitch · A4 = 440 Hz':'You can pause and finish later.'}</p><button class="primary record">${icon(busy?'stop':accepted||done?'check':'mic')}${done?'Calculate tuning targets':busy?'Stop recording':accepted?'Next note':p.take===1?'Record second strike':'Record first strike'}</button>`;
}
function reset(){timers.forEach(clearTimeout);timers=[];$('#state').value='flat';document.querySelectorAll('.phone').forEach(p=>{p.midi=69;p.paused=false;p.index=4;p.take=0;p.recording=false;p.dataset.type==='tune'?renderTune(p):renderCal(p)})}reset();
$('#state').onchange=()=>document.querySelectorAll('[data-type="tune"]').forEach(renderTune);
$('#text-size').onchange=()=>document.querySelectorAll('.phone').forEach(p=>p.style.setProperty('--text-scale',$('#text-size').value));
$('#width').onchange=()=>document.documentElement.style.setProperty('--phone-width',$('#width').value+'px');$('#reset').onclick=reset;
$('#screens').onclick=e=>{const b=e.target.closest('button'),p=b?.closest('.phone');if(!b||!p)return;
if(b.dataset.step){p.midi=Math.max(21,Math.min(108,p.midi+Number(b.dataset.step)));renderTune(p)}
if(b.classList.contains('listen')){p.paused=!p.paused;renderTune(p);p.querySelector('.listen').focus()}
if(b.classList.contains('details')){const d=$('#details');d.dataset.theme=p.dataset.theme;d.showModal()}
if(b.classList.contains('record')){if(p.recording){p.recording=false;clearTimeout(p.timer)}else if(p.index>=9){p.querySelector('.capture-status').innerHTML='<strong>Ready to tune</strong><p>This prototype stops here. In the app, calculation would open piano tuning.</p>';return}else if(p.take===2){p.index++;p.take=0}else{p.recording=true;p.timer=setTimeout(()=>{if(!p.recording)return;p.recording=false;p.take++;renderCal(p)},1600);timers.push(p.timer)}renderCal(p);p.querySelector('.record').focus()}
if(b.classList.contains('appearance')){const old=p.querySelector('.theme-picker');if(old){old.remove();return}const panel=document.createElement('div');panel.className='theme-picker';panel.setAttribute('role','group');panel.setAttribute('aria-label','Appearance');panel.innerHTML=['light','dark','system'].map(t=>`<button data-mode="${t}" aria-pressed="${(p.mode||p.dataset.theme)===t}">${t[0].toUpperCase()+t.slice(1)}</button>`).join('');p.querySelector('.app-head').append(panel);panel.querySelector('[aria-pressed="true"]').focus()}
if(b.dataset.mode){p.mode=b.dataset.mode;p.dataset.theme=p.mode==='system'?(matchMedia('(prefers-color-scheme:dark)').matches?'dark':'light'):p.mode;p.querySelector('.appearance').innerHTML=icon(p.mode==='system'?'system':p.dataset.theme==='dark'?'moon':'sun');p.querySelector('.theme-picker').remove();p.querySelector('.appearance').focus()}
};
document.addEventListener('keydown',e=>{const panel=e.target.closest('.theme-picker');if(!panel)return;const bs=[...panel.querySelectorAll('button')],i=bs.indexOf(document.activeElement);if(e.key==='Escape'){const p=panel.closest('.phone');panel.remove();p.querySelector('.appearance').focus()}if(['ArrowDown','ArrowUp','Home','End'].includes(e.key)){e.preventDefault();bs[e.key==='Home'?0:e.key==='End'?2:(i+(e.key==='ArrowDown'?1:2))%3].focus()}});
document.addEventListener('click',e=>document.querySelectorAll('.theme-picker').forEach(panel=>{if(!panel.contains(e.target)&&!e.target.closest('.appearance'))panel.remove()}));
$('#details').querySelectorAll('.close').forEach(b=>b.onclick=()=>$('#details').close());
